In [1]:
import pandas as pd
import numpy as np
import os
import glob

In [25]:
master_df = pd.DataFrame(columns=['File_Name', 'Full_Path', 'VT_Report_Path'])

In [67]:
df

,File_Name,Full_Path,VT_Report_Path
0,035,/mnt/data_disk1/mabon/datacopy/MLSec20/origina...,/home/mabon/research/Autoyara/YaraResults/viru...
1,027,/mnt/data_disk1/mabon/datacopy/MLSec20/origina...,/home/mabon/research/Autoyara/YaraResults/viru...
2,019,/mnt/data_disk1/mabon/datacopy/MLSec20/origina...,/home/mabon/research/Autoyara/YaraResults/viru...
3,038,/mnt/data_disk1/mabon/datacopy/MLSec20/origina...,/home/mabon/research/Autoyara/YaraResults/viru...
4,048,/mnt/data_disk1/mabon/datacopy/MLSec20/origina...,/home/mabon/research/Autoyara/YaraResults/viru...
...,...,...,...
32013,7761626135c7984b9dd7a01800cb9803b14b8749.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
32014,7760043705bcecd679e62d54fcbd54e1e251fcb0.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
32015,77612de774d3075f0c7855d589962880dd148a3d.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
32016,777e87a6352eff48a5dbe09c9189f598bdcd7d10.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
32017,7774658aa884314d1bc5ed7f536d99f4a66dadd3.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...

In [69]:
df.to_csv('/home/mabon/research/Autoyara/YaraResults/MasterCSV1.csv', index=False)

In [70]:

# 1. Remove the 'hash' column
df = master_df.drop(columns=['hash'], errors='ignore')

# 2. Drop duplicate rows and count how many were removed
original_count = len(df)
df = df.drop_duplicates()
removed_duplicates = original_count - len(df)
print(f"Removed {removed_duplicates} duplicate rows.")

# 3. Check if VT_Report_Path files exist
df['VT_Exists'] = df['VT_Report_Path'].apply(lambda x: os.path.exists(x))
missing_count = (~df['VT_Exists']).sum()
print(f"{missing_count} VT report paths not found on disk.")

# (Optional) Drop the temporary column if you want a clean DataFrame
df = df.drop(columns=['VT_Exists'])

Removed 0 duplicate rows.
0 VT report paths not found on disk.

In [45]:
totalPass=0
totalFail=0
mainCsv=('/home/mabon/research/Autoyara/YaraResults/masterCSV/datasetMalwarePE.csv')
reports_root=('/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/')

In [62]:
p=('/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/indexCSV/vt_report_paths_UCSB.JP.csv')
df=pd.read_csv(p)
df

,File_Name,Full_Path,VT_Report_Path
0,888dc1dc9448ec101c5516442dc6fd45880f8bce.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,vt_reports/vt_reports_UCSB.JP/vt_report_888dc1...
1,88e345b1a5b836af84ae2d4a1bd748c90b3f3bc4.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,vt_reports/vt_reports_UCSB.JP/vt_report_88e345...
2,88e365bfa862a5ac459746f3ff7a0c0df897e334.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,vt_reports/vt_reports_UCSB.JP/vt_report_88e365...
3,88e5e7587f9c679661283844fcb8e08b3e2df43c.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,vt_reports/vt_reports_UCSB.JP/vt_report_88e5e7...
4,88eac7ab00a6b7bfac49998af93ea5cd1b2c1b7d.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,vt_reports/vt_reports_UCSB.JP/vt_report_88eac7...
...,...,...,...
6516,7761626135c7984b9dd7a01800cb9803b14b8749.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,vt_reports/vt_reports_UCSB.JP/vt_report_776162...
6517,7760043705bcecd679e62d54fcbd54e1e251fcb0.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,vt_reports/vt_reports_UCSB.JP/vt_report_776004...
6518,77612de774d3075f0c7855d589962880dd148a3d.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,vt_reports/vt_reports_UCSB.JP/vt_report_77612d...
6519,777e87a6352eff48a5dbe09c9189f598bdcd7d10.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,vt_reports/vt_reports_UCSB.JP/vt_report_777e87...
6520,7774658aa884314d1bc5ed7f536d99f4a66dadd3.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,vt_reports/vt_reports_UCSB.JP/vt_report_777465...

In [26]:

# Convert to string before applying string operation
result['VT_Report_Path'] = result['VT_Report_Path'].astype(str)
c=0
# Filter rows where VT_Report_Path file exists
for _, row in result.iterrows():
    if os.path.exists(row['VT_Report_Path']):
        master_df = pd.concat([master_df, pd.DataFrame([row])], ignore_index=True)
    else:
        c+=1
print(c)

1529

In [64]:
reports_root=('/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_CodexGiga/')

report_files = glob.glob(os.path.join(reports_root, "vt_report_*_codex_*.json"))

# Step 1: Build a mapping from hash to full report path
report_map = {}
for path in report_files:
    filename = os.path.basename(path)
    # Extract the hash from the filename
    parts = filename.split("_")
    if len(parts) >= 3:
        file_hash = parts[2]  # This assumes the hash is the 3rd item in split list
        report_map[file_hash] = path

# Step 2: Add 'hash' column to df
df['hash'] = df['File_Name'].str.extract(r'^([a-f0-9]{40})')

# Step 3: Map the hash to report path
df['VT_Report_Path'] = df['hash'].map(report_map)

In [33]:

# Step 4: Filter only rows that have a report and append to master_df
matching_rows = df[df['VT_Report_Path'].notna()]
master_df = pd.concat([master_df, matching_rows], ignore_index=True)

In [9]:
import os
import pandas as pd
from tqdm import tqdm

# Base directory
reports_root = '/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/'

# List of relative paths from your input
csv_paths = [
    # "./virustotalReports/vt_reports_MLSec20/vt_report_paths.csv",
    # "./virustotalReports/vt_reports_MLSec21/vt_report_paths.csv",
    # "./virustotalReports/vt_reports_Honeypots/vt_report_paths.csv",
    # "./virustotalReports/vt_reports_CodexGiga/run1/vt_report_paths.csv",
    # "./virustotalReports/vt_reports_CodexGiga/vt_report_paths.csv",
    # "./virustotalReports/vt_reports_CodexGiga/vt_report_paths_CodexGiga.csv",
    # "./virustotalReports/vt_reports_MLSec19/vt_report_paths.csv",
    # "./virustotalReports/vt_reports_APT/vt_report_paths.csv",
    # "./indexCSV/vt_report_paths_Stefano.csv",
    # "./indexCSV/vt_report_paths_BluePex.csv",
    # "./indexCSV/vt_report_paths_MLSec19.csv",
    # "./indexCSV/vt_report_paths_evasive-it.csv",
    # "./indexCSV/vt_report_paths_BB.csv",
    "./indexCSV/vt_report_paths_UCSB.csv",
    "./indexCSV/vt_report_paths_UCSB.JP.csv",
]

# Resolve to full paths
full_csv_paths = [os.path.join(reports_root, path.lstrip("./")) for path in csv_paths]

# Read and merge all CSVs
merged_df = pd.DataFrame()
for path in tqdm(full_csv_paths, desc="Reading CSVs"):
    try:
        df = pd.read_csv(path)
        df['Source_CSV'] = os.path.basename(path)  # Optional: track source
        merged_df = pd.concat([merged_df, df], ignore_index=True)
    except Exception as e:
        print(f"❌ Error reading {path}: {e}")

# Optional: Save merged result
# merged_df.to_csv("merged_vt_report_paths.csv", index=False)

print(f"\n✅ Merged DataFrame shape: {merged_df.shape}")

Reading CSVs: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 70.57it/s]

✅ Merged DataFrame shape: (42924, 4)

In [18]:

base_dir = "/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports"

# Safely convert to string and strip leading slashes (skip NaNs)
merged_df['VT_Report_Path'] = merged_df['VT_Report_Path'].dropna().astype(str).str.lstrip('/')

# Now apply join, handling any remaining non-string entries safely
merged_df['VT_Report_Path'] = merged_df['VT_Report_Path'].apply(
    lambda x: os.path.join(base_dir, x) if isinstance(x, str) else x
)

In [27]:
merged_df['VT_Report_Path'] = merged_df['VT_Report_Path'].str.replace("vt_reports/", "", n=1)

'/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/MLSec20_pe_files/vt_report_019_20250313_222627.json'

In [40]:
list(merged_df["VT_Report_Path"])[1000:20000]

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 ...]

In [26]:

# Normalize File_Name columns (e.g., strip extensions from df_reports if needed)
df['File_Name_clean'] = df['File_Name'].astype(str)

# Perform anti-join: files in master but not in reports
df_missing = df[~df['File_Name'].isin(merged_df['File_Name'])].copy()

# Keep only relevant columns
df_missing_final = df_missing[['File_Name', 'Full_Path']]

# Optional: save to CSV
# df_missing_final.to_csv("missing_reports.csv", index=False)

# Print summary
print(f"❌ Total missing files: {len(df_missing_final)}")

❌ Total missing files: 39337

In [16]:
df_missing_final

,File_Name,Full_Path
25786,McUtil.dll,/mnt/data_disk1/mabon/datacopy/APTs/iec56w4ibo...
25911,AudioSes.dll,/mnt/data_disk1/mabon/datacopy/APTs/iec56w4ibo...
26231,WindowsAccessBridge.dll,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...
26232,messenger.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...
26233,tcpip.cpl,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...
...,...,...
66002,wVersion748.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2019-0...
66003,euminstall.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2019-0...
66004,index.html.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2016-1...
66005,NF_PAGAMENTO_00121222_11_2016.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2016-1...
66006,3z0r0D1T0E1E.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2016-1...

In [71]:
import pandas as pd

In [73]:
df=pd.read_csv('/home/mabon/research/Autoyara/YaraResults/virusTotalRaw_Stage/MasterCSV1.csv')
df

,File_Name,Full_Path,VT_Report_Path
0,035,/mnt/data_disk1/mabon/datacopy/MLSec20/origina...,/home/mabon/research/Autoyara/YaraResults/viru...
1,027,/mnt/data_disk1/mabon/datacopy/MLSec20/origina...,/home/mabon/research/Autoyara/YaraResults/viru...
2,019,/mnt/data_disk1/mabon/datacopy/MLSec20/origina...,/home/mabon/research/Autoyara/YaraResults/viru...
3,038,/mnt/data_disk1/mabon/datacopy/MLSec20/origina...,/home/mabon/research/Autoyara/YaraResults/viru...
4,048,/mnt/data_disk1/mabon/datacopy/MLSec20/origina...,/home/mabon/research/Autoyara/YaraResults/viru...
...,...,...,...
32013,7761626135c7984b9dd7a01800cb9803b14b8749.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
32014,7760043705bcecd679e62d54fcbd54e1e251fcb0.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
32015,77612de774d3075f0c7855d589962880dd148a3d.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
32016,777e87a6352eff48a5dbe09c9189f598bdcd7d10.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
32017,7774658aa884314d1bc5ed7f536d99f4a66dadd3.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...

In [8]:
import pandas as pd
import os
vt_directory = '/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/'
df=pd.read_csv('/home/mabon/research/Autoyara/YaraResults/masterCSV/familyDataCSV/BB_pe_files.csv')
df

,File_Name,Full_Path
0,WindowsAccessBridge.dll,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...
1,messenger.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...
2,tcpip.cpl,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...
3,Donwload-Boleto-12-11-2013.cpl,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...
4,km5rcheim.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...
...,...,...
39771,wVersion748.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2019-0...
39772,euminstall.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2019-0...
39773,index.html.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2016-1...
39774,NF_PAGAMENTO_00121222_11_2016.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2016-1...
39775,3z0r0D1T0E1E.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2016-1...

In [10]:
vt_files = os.listdir(vt_directory)
vt_file_map = {f.replace('.json', ''): os.path.join(vt_directory, f) for f in vt_files if f.endswith('.json')}

# Function to get matching VT path
def get_vt_path(file_name):
    return vt_file_map.get(file_name, None)

# Apply to dataframe
df['VT_Report_Path'] = df['File_Name'].apply(get_vt_path)

In [11]:
df

,File_Name,Full_Path,VT_Report_Path
0,WindowsAccessBridge.dll,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
1,messenger.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
2,tcpip.cpl,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
3,Donwload-Boleto-12-11-2013.cpl,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
4,km5rcheim.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
...,...,...,...
39771,wVersion748.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2019-0...,/home/mabon/research/Autoyara/YaraResults/viru...
39772,euminstall.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2019-0...,/home/mabon/research/Autoyara/YaraResults/viru...
39773,index.html.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2016-1...,/home/mabon/research/Autoyara/YaraResults/viru...
39774,NF_PAGAMENTO_00121222_11_2016.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2016-1...,/home/mabon/research/Autoyara/YaraResults/viru...
39775,3z0r0D1T0E1E.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2016-1...,/home/mabon/research/Autoyara/YaraResults/viru...

In [13]:
df2=pd.read_csv('/home/mabon/research/Autoyara/YaraResults/virusTotalRaw_Stage/MasterCSV1.csv')

In [16]:
l=[df,df2]
result = pd.concat(l)

In [17]:
result

,File_Name,Full_Path,VT_Report_Path
0,WindowsAccessBridge.dll,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
1,messenger.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
2,tcpip.cpl,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
3,Donwload-Boleto-12-11-2013.cpl,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
4,km5rcheim.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
...,...,...,...
32013,7761626135c7984b9dd7a01800cb9803b14b8749.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
32014,7760043705bcecd679e62d54fcbd54e1e251fcb0.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
32015,77612de774d3075f0c7855d589962880dd148a3d.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
32016,777e87a6352eff48a5dbe09c9189f598bdcd7d10.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
32017,7774658aa884314d1bc5ed7f536d99f4a66dadd3.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...

In [78]:
len(vt_files)

52949

In [80]:
# Get set of VT_Report_Path from DataFrame
vt_report_paths = set(df['VT_Report_Path'].str.strip())

# Find paths in vt_files that are not in vt_report_paths
missing_paths = [path for path in vt_files if path not in vt_report_paths]

# Display results
if missing_paths:
    print("Paths in /home/mabon/research/Autoyara/YaraResults/virusTotalRaw/ (including subdirectories) not in DataFrame:")
    for path in missing_paths:
        print(path)
else:
    print("All paths in the directory (including subdirectories) are present in the DataFrame.")

Paths in /home/mabon/research/Autoyara/YaraResults/virusTotalRaw/ (including subdirectories) not in DataFrame:
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Generic_Guide.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/DSC93290.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Ibridge.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/CurriculumVitae-AnaClaudiaBorges-UFBH-200603290043005400439540.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/CobrancaJudicial0413.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/WLANExt.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/0B_xUOZNXHP23cGxmQzdSekZQdEU_e_download.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Anexo.doc.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/notas-fiscais-referenciadas-de-produtor.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/xxlimauu2277.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/posto.pdf.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/bpie8266.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/i03vpcv8.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/hljukmsu.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/w4r4.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/mshytmid.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/DX1ysSy7iN028Ojh3TDckQn1tG.tmp.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/protect.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/lorf9674.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Aqupunzai250.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/165637.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/consultar_entrega.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Notificacao_201405000177.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/tpgq5809.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/PER-DEIC-Intimacao.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/lixhunt.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/2P5r2K.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/OLEAUT32.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/CURRICULUM.DOC.scr.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/gbwertp.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/NoxEmulator.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/BlackBarryProtect.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/jusheds.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Anexo-04531212240001.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/oldbygirls.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/copia_chequecleosvaldo2014.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/2p5Z0W.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Segundaviatitulo02.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/dacomdiz.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/tdet32mnd.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/DSC001.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/mz8h.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Planilha_OrÃ§amento.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/cYnXBcS.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/2B3U3k000i0b.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Visualizar-Documento-200390000120305064003000020110.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/PROTESTO019838192839282UUHAHHUAUHHUHAHAHAUHAHAH.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/aplicdata.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/4162bol.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Opera.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/260u91tn1.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/VERSÃTIL.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Planilha_Documento_50390.docx_.scr.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/NotaFiscal34.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Visualizar_Boleto_de_Cobranca.cmd.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Orcamento_Comercial.xls.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/arquivo.pdf.......................................................................................................................exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/NF-31-1303-66.317.835.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/A.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/comprovante192122.com.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/X9vaNgRO.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/KbrftfA.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/msgs.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Putaria0485_2022726775.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/dy0C4DiY3Y.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/setup_a7158.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/cartoes_especiais.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/picanha.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/fotos_0092014.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/sharenc.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Sub.esF.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/DoeaupG.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/ConversaBate-Papo-Facebook.jpg_..exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/StartUpdatesc_8298852.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/HostsControl.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/escams.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/MZKwgPrnalxX.exe.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/ARQV0201206.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/2hx0.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/afip.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/multiMessenger.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Conversas_2012.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/ffox.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/TItZjRlZDg5ZDI1MGU0_e_download.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/fybj.sys.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Visualizar_Notificacao102013.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/k5y2.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/video_Sensual_IsisValverde.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/dynamikyhwwj.gif.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Nota-Fiscal-Eletronica-30-10-2013.zip.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/ExpIorer.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/aren.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/N_893200489_09_10_2015.pdf.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/dDFwc3M_e_download_cli_Cliente.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/jllf3577.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Imprimir2via-boleto.com.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/E-CobranÃ§aCAIXA-BOLETO-2014021229283843.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/102-4378.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/OcorrÃªncia(B.O.).cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/2_36125541_directDownload_true.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/cl1.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/65e46617.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/XBOX2012.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/flash.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/ZFmzNI7yzk.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/central_1003456c_c4c.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/xxx2.jpg.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/kren.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/SysP1972.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Comprovante_de_deposito.PDF.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/hulk.jpg.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/ou147.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/roughage.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/inetwiz.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/iasres.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Boleto_em_atraso_100002006836293.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Updateh.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/SimpCertificates999.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/d.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/uprlpu.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/jeNUh.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Cheque_Contrato_Debitos.pdf.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/verificacao_processo_doc.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/s_protoc701900137664395_98.com.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/6Z7f2Z.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Boleto_vencido.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/UpSyscleosvaldo.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Documento-Planilha.DOCX_.scr.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/NFS-e_00439047507344753407.xlm_ihswqdto.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/0B1uSUXSht1H_U19UQXZ3QUxUdjQ.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/arquivo.php...................................................................................................................................................exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/debitos_serasa.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/des.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Tioqulecik1614.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/agimalfmoto.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Mensagem_de_Voz_N_487476567575677.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Comprovante_tf_800019020150183.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/WindowNT.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Recibo_de_Pagamento.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/D0VW3FzBk6.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Arquivo.00982386.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/AdminUpdate002912.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/zv6i5fysw.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/yurprmf.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Notaf-ecleosvaldo2014.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/NF-PDF-340290.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/AnexoLivecleosvaldo.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Nota_Fiscal_Eletronica_Encaminhada_Prods_BR.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/taelord.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Deposito_Sexta.scr.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/chrome_app.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Documento_Anexo_Planilha.docx_.scr.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/facebookfotos03.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Nota_Fiscal_Eletronica_pdf.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/c464adc5451b0bae4c.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/New.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/avgrs.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/EnemProtocolo_285837923.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/bwertyugtre54.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/ipHkzKatYEtGcrXjL.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/wJcgqL7cxpa4e0PqqxPhJo0ek6y1IZGT3Kc1.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/drweb.cpl.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/687897305.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/qLYrcLzmtppfgtQOjNyXoOJf.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/DOC789456321.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/0u0z1T0A1d3b.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Demonstrativo-Debitos_NqXBFr.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/qqhd3725.dll.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Dc11.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/sub.png.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/correcao.png.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/BOL-8912COD2099_070114.exe.json
/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/virustotalReports/vt_reports_BB/Cheque-devolvido-id-019920000900303399.pdf.cpl.json

In [84]:
df_big=pd.read_csv('/home/mabon/research/Autoyara/YaraResults/masterCSV/datasetMalwarePE.csv')

In [90]:
df_big

,File_Name,Full_Path
0,68f22901ca321609823c5211354ef8946432d77be33150...,/mnt/data_disk1/mabon/datacopy/evasive-it/2021...
1,a470823db33706bd6ea4768a5240e82815fac99ce26dbd...,/mnt/data_disk1/mabon/datacopy/evasive-it/2021...
2,21fc6ae8f7c0619af4c03ce300bb271f3d3ec43cd196bb...,/mnt/data_disk1/mabon/datacopy/evasive-it/2021...
3,4149f025cfce38098d9b8a048c169651a38d312ed6e026...,/mnt/data_disk1/mabon/datacopy/evasive-it/2021...
4,55a3c455cfbd70fd91663e251ea65db6452edbb0d730c8...,/mnt/data_disk1/mabon/datacopy/evasive-it/2021...
...,...,...
71700,b0faac097178e37320f1efc7beeab100f8b18f5c67936e...,/mnt/data_disk1/mabon/datacopy/Stefano/b0faac0...
71701,b45e799424c18b154a7c725e8b9ae96e81d6f3df076a0e...,/mnt/data_disk1/mabon/datacopy/Stefano/b45e799...
71702,9b22cf8ca8d5cbd55136c7d19901e0a83da7aa6dd0b3f3...,/mnt/data_disk1/mabon/datacopy/Stefano/9b22cf8...
71703,32f1d943c84fc251594546b49a4e75765cf71dde2a41a5...,/mnt/data_disk1/mabon/datacopy/Stefano/32f1d94...
71704,415fa60211b6372d450324519623e7ad658b080dce2ab7...,/mnt/data_disk1/mabon/datacopy/Stefano/415fa60...

In [92]:
# Ensure both columns are strings for safe comparison
master_fnames_set = set(master_df['File_Name'].astype(str))
df_big['File_Name'] = df_big['File_Name'].astype(str)

# Filter df_big to exclude File_Names that exist in master_df
df_big_filtered = df_big[~df_big['File_Name'].isin(master_fnames_set)].copy()

In [93]:
df_big_filtered

,File_Name,Full_Path
20095,aee445698df36b377b914912f5acd1c44b31aae2.codex,/mnt/data_disk1/mabon/datacopy/CodexGiga/aee44...
20099,0b0cdf47363fd27bccbfba6d47b842e44a365723.codex,/mnt/data_disk1/mabon/datacopy/CodexGiga/0b0cd...
20104,ea0cfe60a7b7168c42c0e86e15feb5b0c9674029.codex,/mnt/data_disk1/mabon/datacopy/CodexGiga/ea0cf...
20107,ad969ce312ec82d0e4094337fc142d9ea76b562d.codex,/mnt/data_disk1/mabon/datacopy/CodexGiga/ad969...
20108,7582cedd4f69a27cb09db643e31d3bfdf1aabdb4.codex,/mnt/data_disk1/mabon/datacopy/CodexGiga/7582c...
...,...,...
66002,wVersion748.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2019-0...
66003,euminstall.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2019-0...
66004,index.html.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2016-1...
66005,NF_PAGAMENTO_00121222_11_2016.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2016-1...
66006,3z0r0D1T0E1E.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2016-1...

In [96]:
from tqdm import tqdm

In [99]:

# Create an empty DataFrame to store the results
recovered_report_df = pd.DataFrame(columns=['File_Name', 'Full_Path', 'Matched_VT_Report'])

# List to collect rows for appending
new_rows = []

# Use tqdm for the progress bar in the loop
for _, row in tqdm(df_big_filtered.iterrows(), total=len(df_big_filtered), desc="Processing files"):
    file_name = row['File_Name']
    full_path = row['Full_Path']
    
    # Check for a similar report in missing_paths (partial match)
    for missing_path in missing_paths:
        if file_name.lower() in missing_path.lower():  # Similarity check
            # Add the matched row as a dictionary to the list
            new_rows.append({
                'File_Name': file_name,
                'Full_Path': full_path,
                'Matched_VT_Report': missing_path
            })

# If we have any new rows, create a new DataFrame
if new_rows:
    recovered_report_df = pd.concat([recovered_report_df, pd.DataFrame(new_rows)], ignore_index=True)

# Show the results
print(f"Found {len(recovered_report_df)} matches.")

Processing files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 39585/39585 [03:30<00:00, 187.83it/s]

Found 203685 matches.

In [101]:
recovered_report_df[0:3]

,File_Name,Full_Path,Matched_VT_Report
0,HDDFirmware,/mnt/data_disk1/mabon/datacopy/APTs/iec56w4ibo...,/home/mabon/research/Autoyara/YaraResults/viru...
1,GrokKeylogger,/mnt/data_disk1/mabon/datacopy/APTs/iec56w4ibo...,/home/mabon/research/Autoyara/YaraResults/viru...
2,EquationDrugLUTEUSOBSTOS,/mnt/data_disk1/mabon/datacopy/APTs/iec56w4ibo...,/home/mabon/research/Autoyara/YaraResults/viru...

In [102]:
c=0
# Filter rows where VT_Report_Path file exists
for _, row in df.iterrows():
    if os.path.exists(row['VT_Report_Path']):
        master_df = pd.concat([master_df, pd.DataFrame([row])], ignore_index=True)
    else:
        c+=1
print(c)

857

In [103]:
i

/home/mabon

In [27]:
master_df

,File_Name,Full_Path,VT_Report_Path
0,WindowsAccessBridge.dll,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
1,messenger.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
2,tcpip.cpl,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
3,Donwload-Boleto-12-11-2013.cpl,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
4,km5rcheim.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...
...,...,...,...
70260,7761626135c7984b9dd7a01800cb9803b14b8749.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
70261,7760043705bcecd679e62d54fcbd54e1e251fcb0.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
70262,77612de774d3075f0c7855d589962880dd148a3d.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
70263,777e87a6352eff48a5dbe09c9189f598bdcd7d10.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...
70264,7774658aa884314d1bc5ed7f536d99f4a66dadd3.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...

In [29]:
import os

# Assuming df_mast is already created and contains 'VT_Report_Path'
master_df['VT_Path_Exists'] = master_df['VT_Report_Path'].apply(lambda x: os.path.exists(x) if pd.notna(x) else False)

# Optionally, print rows where the path is missing
missing_paths = master_df[~master_df['VT_Path_Exists']]
print(f"Missing VT report paths: {len(missing_paths)}")
print(missing_paths[['File_Name', 'VT_Report_Path']])

Missing VT report paths: 0
Empty DataFrame
Columns: [File_Name, VT_Report_Path]
Index: []

In [36]:
# Duplicates in Full_Path
duplicate_full_paths = master_df[master_df.duplicated('Full_Path', keep=False)]
print(f"\nDuplicate Full_Path entries: {len(duplicate_full_paths)}")
print(duplicate_full_paths[['File_Name', 'Full_Path']])

# Remove all rows with duplicate Full_Path
master_df = master_df[~master_df.duplicated('Full_Path', keep=False)].reset_index(drop=True)
print(f"\nRemaining rows after removing duplicates in Full_Path: {len(master_df)}")

# Duplicates in VT_Report_Path (ignoring NaNs)
duplicate_vt_paths = master_df[master_df['VT_Report_Path'].notna() & master_df.duplicated('VT_Report_Path', keep=False)]
print(f"\nDuplicate VT_Report_Path entries: {len(duplicate_vt_paths)}")
print(duplicate_vt_paths[['File_Name', 'VT_Report_Path']])

Duplicate Full_Path entries: 0
Empty DataFrame
Columns: [File_Name, Full_Path]
Index: []

Remaining rows after removing duplicates in Full_Path: 70265

Duplicate VT_Report_Path entries: 22989
                               File_Name  \
0                WindowsAccessBridge.dll
1                          messenger.exe
2                              tcpip.cpl
10             Proposta_Creative_PDF.cpl
11                        servicesnb.exe
...                                  ...
39094                       hostswd2.exe
39095                        hostswd.exe
39098                             manual
39101                     index.html.exe
39102  NF_PAGAMENTO_00121222_11_2016.exe

                                          VT_Report_Path
0      /home/mabon/research/Autoyara/YaraResults/viru...
1      /home/mabon/research/Autoyara/YaraResults/viru...
2      /home/mabon/research/Autoyara/YaraResults/viru...
10     /home/mabon/research/Autoyara/YaraResults/viru...
11     /home/mabon/research/Autoyara/YaraResults/viru...
...                                                  ...
39094  /home/mabon/research/Autoyara/YaraResults/viru...
39095  /home/mabon/research/Autoyara/YaraResults/viru...
39098  /home/mabon/research/Autoyara/YaraResults/viru...
39101  /home/mabon/research/Autoyara/YaraResults/viru...
39102  /home/mabon/research/Autoyara/YaraResults/viru...

[22989 rows x 2 columns]

In [46]:
# Drop all rows where Full_Path is duplicated (i.e., keep only unique Full_Path rows)
df_mast_unique = master_df[~master_df.duplicated('VT_Report_Path', keep=False)].reset_index(drop=True)

# Show result
print(f"Remaining rows after removing duplicates: {len(df_mast_unique)}")

Remaining rows after removing duplicates: 47276

In [49]:
len(list(master_df["VT_Report_Path"].unique()))

52014

In [50]:
master_df = master_df[master_df["VT_Report_Path"].duplicated(keep=False) == False]

In [54]:
master_df.to_csv('/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/MAINRerports.csv')

In [53]:
c=0
# Filter rows where VT_Report_Path file exists
for _, row in master_df.iterrows():
    if os.path.exists(row['VT_Report_Path']):
        continue
    else:
        c+=1
print(c)

0

In [83]:
df_M=pd.read_csv('/home/mabon/research/Autoyara/YaraResults/masterCSV/datasetMalwarePE.csv')

In [84]:
df_M

,File_Name,Full_Path
0,68f22901ca321609823c5211354ef8946432d77be33150...,/mnt/data_disk1/mabon/datacopy/evasive-it/2021...
1,a470823db33706bd6ea4768a5240e82815fac99ce26dbd...,/mnt/data_disk1/mabon/datacopy/evasive-it/2021...
2,21fc6ae8f7c0619af4c03ce300bb271f3d3ec43cd196bb...,/mnt/data_disk1/mabon/datacopy/evasive-it/2021...
3,4149f025cfce38098d9b8a048c169651a38d312ed6e026...,/mnt/data_disk1/mabon/datacopy/evasive-it/2021...
4,55a3c455cfbd70fd91663e251ea65db6452edbb0d730c8...,/mnt/data_disk1/mabon/datacopy/evasive-it/2021...
...,...,...
71700,b0faac097178e37320f1efc7beeab100f8b18f5c67936e...,/mnt/data_disk1/mabon/datacopy/Stefano/b0faac0...
71701,b45e799424c18b154a7c725e8b9ae96e81d6f3df076a0e...,/mnt/data_disk1/mabon/datacopy/Stefano/b45e799...
71702,9b22cf8ca8d5cbd55136c7d19901e0a83da7aa6dd0b3f3...,/mnt/data_disk1/mabon/datacopy/Stefano/9b22cf8...
71703,32f1d943c84fc251594546b49a4e75765cf71dde2a41a5...,/mnt/data_disk1/mabon/datacopy/Stefano/32f1d94...
71704,415fa60211b6372d450324519623e7ad658b080dce2ab7...,/mnt/data_disk1/mabon/datacopy/Stefano/415fa60...

In [58]:
new_df = pd.DataFrame(columns=['File_Name', 'Full_Path'])

# Perform an anti-join to find new entries not in df_M
requrey_df = new_df.merge(df_M[['File_Name', 'Full_Path']], 
                          on=['File_Name', 'Full_Path'], 
                          how='left', 
                          indicator=True)

# Keep only the rows not present in df_M
requrey_df = requrey_df[requrey_df['_merge'] == 'left_only'].drop(columns=['_merge']).reset_index(drop=True)

In [85]:
full_paths_to_remove=list(master_df["Full_Path"])

In [87]:
# Drop rows where Full_Path is in the list of full_paths_to_remove
df_M = df_M[~df_M['Full_Path'].isin(full_paths_to_remove)]

# Reset index if needed
df_M = df_M.reset_index(drop=True)

In [89]:
df_M.to_csv('/home/mabon/research/Autoyara/YaraResults/virusTotalRaw/MissedReports.csv')

In [74]:
merged = df_M.merge(master_df, on=['Full_Path'], how='right', indicator=True)

In [78]:
merged

,File_Name,Full_Path,VT_Report_Path,VT_Path_Exists,_merge
0,Donwload-Boleto-12-11-2013.cpl,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...,True,right_only
1,km5rcheim.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...,True,right_only
2,Boleto_Imperio_Cobranca.2a_via.cpl,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...,True,right_only
3,0dj66n59g.exe,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...,True,right_only
4,FOTODSC567.cpl,/mnt/data_disk1/mabon/datacopy/BB/Files/2013-1...,/home/mabon/research/Autoyara/YaraResults/viru...,True,right_only
...,...,...,...,...,...
47271,7761626135c7984b9dd7a01800cb9803b14b8749.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...,True,right_only
47272,7760043705bcecd679e62d54fcbd54e1e251fcb0.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...,True,right_only
47273,77612de774d3075f0c7855d589962880dd148a3d.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...,True,right_only
47274,777e87a6352eff48a5dbe09c9189f598bdcd7d10.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...,True,right_only
47275,7774658aa884314d1bc5ed7f536d99f4a66dadd3.bin,/mnt/data_disk1/mabon/datacopy/UCSB.JP/data_fe...,/home/mabon/research/Autoyara/YaraResults/viru...,True,right_only